#%RAML 1.0 Library
types:
  SchedulerType:
    type: string
    enum: [CONTINUOUS, MANUAL]
    description: |
      Scheduler type. Supported scheduler types are CONTINUOUS and MANUAL.
  Scheduler:
    type: object
    description: A scheduler declaration
    properties:
      type:
        type: SchedulerType
        default: CONTINUOUS
      lol:
        type: integer
        format: int32
        default: 0
